// <auto-generated />
using System;
using Dotnetstore.Business.Repository.EF.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dotnetstore.Business.Repository.EF.Migrations
{
    [DbContext(typeof(BusinessContext))]
    [Migration("20230216124830_v100")]
    partial class v100
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.3");

            modelBuilder.Entity("Dotnetstore.Domain.Business.OwnCompany", b =>
                {
                    b.Property<Guid?>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CorporateID")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<Guid?>("CreatedByID")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CreatedDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("DeletedByID")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<bool?>("IsDeleted")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisposed")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsGDPR")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsSystem")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsUpdated")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsVisible")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("LastUpdatedByID")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUpdatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("OwnCompanies");
                });
#pragma warning restore 612, 618
        }
    }
}
